version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  db:
    image: pgvector/pgvector:pg16
    shm_size: 1g
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jobee_dev
      POSTGRES_PASSWORD: 319298
      POSTGRES_DB: jobee_dev

  # api:
  #   build: ./api
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     DATABASE_HOST: db
  #     DATABASE_USER: user
  #     DATABASE_PASSWORD: password
  #     DATABASE_NAME: mydatabase

volumes:
  redis_data:
  postgres-data: